### ISSUE TITLE
語録追加

### ISSUE THREAD

**Issue by Ran350** [ygkn/abebot#8]
- 勝ち組じゃん 
- 天才じゃん 
- 寿司打は呼吸 
- リーダブルコードを貸すのは，友達にフリスク渡すレベルで失礼よ 
- やれない理由ではなく，やれる方法を考えていく 
- 慣れてないものをクソと表現するのはよくないよね，という個人の矜持があったりする 
- お前らが期待しすぎたのは環境じゃなくて自分じゃねーの？ 
- 単位が落ちたのではない、我々が上がったのだ
- 天地がひっくり返ってもそんなことは無いんで安心してちょ
 - 〇〇くんが焼き肉奢りたそうにしてたから〜

**Comment by ygkn** [comment]
Good Issue.
